{% set name = "langchain" %}
{% set version = "0.3.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1d72aa39546a23db08492d7228464af35c9ee83379945535ceef877340d2a3a

build:
  number: 0
  skip: True # [py<39]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - langchain-server = langchain.server:main

requirements:
  host:
    - pip
    - python
    - pdm-backend
  run:
    - python
    - langchain-core <1.0.0,>=0.3.58
    - langchain-text-splitters <1.0.0,>=0.3.8
    - langsmith <0.4,>=0.1.17
    - pydantic <3.0.0,>=2.7.4
    - SQLAlchemy <3,>=1.4
    - requests <3,>=2
    - PyYAML >=5.3
    - async-timeout <5.0.0,>=4.0.0  # [py<311]
  run_constrained:
    - langchain-community
    - langchain-anthropic
    - langchain-openai
    - langchain-azure-ai
    - langchain-cohere
    - langchain-google-vertexai
    - langchain-google-genai
    - langchain-fireworks
    - langchain-ollama
    - langchain-together
    - langchain-mistralai
    - langchain-huggingface
    - langchain-groq
    - langchain-aws
    - langchain-deepseek
    - langchain-xai
    - langchain-perplexity

test:
  imports:
    - langchain
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/langchain-ai/langchain
  doc_url: https://python.langchain.com/
  dev_url: https://github.com/hwchase17/langchain
  summary: Building applications with LLMs through composability
  description: |
    LangChain is a framework for developing applications powered by language models (LLMs).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
