{% set name = "langchain" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/langchain-ai/langchain/archive/refs/tags/{{ name }}=={{ version }}.tar.gz
  sha256: 0acf878e9a1ed85453262dec065c78060a50d71cc91f8ad6dc5792ba7debd3e6

build:
  number: 0
  skip: True # [py<39 or s390x]
  script: 
    - {{ PYTHON }} -m pip install ./libs/langchain -vv --no-deps --no-build-isolation
  entry_points:
    - langchain-server = langchain.server:main

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - aiohttp >=3.8.3,<4.0.0
    - async-timeout >=4.0.0,<5.0.0  # [py<311]
    - langchain-core >=0.3.21,<0.4.0
    - langchain-text-splitters >=0.3.0,<0.4.0
    - langsmith >=0.1.17,<0.2.0
    - numpy >=1.22.4,<2.0.0  # [py<312]
    - numpy >=1.26.2,<3.0.0  # [py>=312]
    - pydantic >=2.7.4,<3.0.0
    - python
    - pyyaml >=5.3
    - requests >=2.0.0,<3.0.0
    - sqlalchemy >=1.4,<3
    - tenacity >=8.1.0,!=8.4.0,<9.0.0
  run_constrained:
    # Copied from conda-forge
    # https://github.com/conda-forge/langchain-feedstock/pull/208

    # based on https://github.com/langchain-ai/langchain/blob/master/libs/langchain/extended_testing_deps.txt
    - jsonschema >=4.22.0,<5
    - numexpr >=2.8.6,<3
    - rapidfuzz >=3.1.1,<4
    - aiosqlite >=0.19.0,<0.20
    # copied from langchain-openai-feedstock
    - openai >=1.26.0,<2.0.0
    - tiktoken >=0.7,<1
    # copied from langchain-anthropic-feedstock
    - anthropic >=0.28.0,<1
    - defusedxml <0.8.0,>=0.7.1
    # copied from langchain-fireworks-feedstock and langchain-together-feedstock
    - fireworks-ai >=0.13.0
    - openai >=1.10.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0
    # copied from langchain-mistralai-feedstock
    - tokenizers >=0.15.1,<1
    - httpx >=0.25.2,<1
    - httpx-sse >=0.3.1,<1
    # copied from langchain-groq-feedstock
    - groq >=0.4.1,<1

test:
  imports:
    - langchain
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/langchain-ai/langchain
  doc_url: https://python.langchain.com/
  dev_url: https://github.com/hwchase17/langchain
  summary: Building applications with LLMs through composability
  description: |
    LangChain is a framework for developing applications powered by language models (LLMs).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
