{% set name = "langchain" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/langchain-ai/langchain/archive/refs/tags/{{ name }}=={{ version }}.tar.gz
  sha256: 0acf878e9a1ed85453262dec065c78060a50d71cc91f8ad6dc5792ba7debd3e6

build:
  number: 0
  skip: True # [py<39 or s390x]
  script: 
    - {{ PYTHON }} -m pip install ./libs/langchain -vv --no-deps --no-build-isolation
  entry_points:
    - langchain-server = langchain.server:main

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - aiohttp >=3.8.3,<4.0.0 #OK
    - async-timeout >=4.0.0,<5.0.0  # [py<311] #OK
    # - dataclasses-json >=0.5.7,<0.7.0
    # - jsonpatch >=1.33,<2.0
    # - langchain-community >=0.0.32,<0.1
    - langchain-core >=0.3.21,<0.4.0 #OK
    - langchain-text-splitters >=0.3.0,<0.4.0 #OK
    - langsmith >=0.1.17,<0.2.0 #OK
    - numpy >=1.22.4,<2.0.0  # [py<312]
    - numpy >=1.26.2,<3.0.0  # [py>=312]
    - pydantic >=2.7.4,<3.0.0 #OK
    - python #OK
    - pyyaml >=5.3 #OK
    - requests >=2.0.0,<3.0.0 #OK
    - sqlalchemy >=1.4,<3 #OK
    - tenacity >=8.1.0,!=8.4.0,<9.0.0 #OK
  run_constrained:
    - aiosqlite >=0.19.0,<0.20.0
    - aleph-alpha-client >=2.15.0,<3.0.0
    - anthropic >=0.3.11,<0.4.0
    - arxiv >=1.4.0,<2.0.0
    - assemblyai >=0.17.0,<0.18.0
    - atlassian-python-api >=3.36.0,<4.0.0
    - awadb >=0.3.9,<0.4.0
    - azure-ai-formrecognizer >=3.2.1,<4.0.0
    - azure-ai-textanalytics >=5.3.0,<6.0.0
    - azure-cognitiveservices-speech >=1.28.0,<2.0.0
    - azure-core >=1.26.4,<2.0.0
    - azure-cosmos >=4.4.0b1,<5.0.0
    - azure-identity >=1.12.0,<2.0.0
    - azure-search-documents 11.4.0b8
    - beautifulsoup4 >=4.0.0,<5.0.0
    - bibtexparser >=1.4.0,<2.0.0
    - cassio >=0.1.0,<0.2.0
    - chardet >=5.1.0,<6.0.0
    - clarifai >=9.1.0
    - clickhouse-connect >=0.5.14,<0.6.0
    - cohere >=4.0.0,<6.0.0
    - couchbase >=4.1.9,<5.0.0
    - dashvector >=1.0.1,<2.0.0
    - databricks-vectorsearch >=0.21,<0.22
    - datasets >=2.15.0,<3.0.0
    - dgml-utils >=0.3.0,<0.4.0
    - docarray >=0.32.0,<0.33.0
    - esprima-python >=4.0.1,<5.0.0
    - faiss-cpu >=1.0.0,<2.0.0
    - feedparser >=6.0.10,<7.0.0
    - fireworks-ai >=0.9.0,<0.10.0
    - geopandas >=0.13.1,<0.14.0
    - gitpython >=3.1.32,<4.0.0
    - google-cloud-documentai <=2.20.1,<3.0.0
    - gql >=3.4.1,<4.0.0
    - hologres-vector >=0.0.6,<0.0.7
    - html2text >=2020.1.16,<2021.0.0
    - huggingface_hub >=0.0.0,<1.0.0
    - javelin-sdk >=0.1.8,<0.2.0
    - jinja2 >=3.0.0,<4.0.0
    - jq >=1.4.1,<2.0.0
    - jsonschema >1
    - langchain-openai >=0.0.2,<0.1
    - lxml >=4.9.3,<6.0.0
    - markdownify >=0.11.6,<0.12.0
    - motor >=3.3.1,<4.0.0
    - msal >=1.25.0,<2.0.0
    - mwparserfromhell >=0.6.4,<0.7.0
    - mwxml >=0.3.3,<0.4.0
    - newspaper3k >=0.2.8,<0.3.0
    - nlpcloud >=1.0.0,<2.0.0
    - numexpr >=2.8.6,<3.0.0
    - openai <2.0.0
    - openapi-pydantic >=0.3.2,<0.4.0
    - openlm >=0.0.5,<0.0.6
    - pandas >=2.0.1,<3.0.0
    - pdfminer-six >=20221105.0.0,<20221106.0.0
    - pgvector >=0.1.6,<0.2.0
    - praw >=7.7.1,<8.0.0
    - psychicapi >=0.8.0,<0.9.0
    - py-trello >=0.19.0,<0.20.0
    - pymupdf >=1.22.3,<2.0.0
    - pypdf >=3.4.0,<4.0.0
    - pypdfium2 >=4.10.0,<5.0.0
    - pyspark >=3.4.0,<4.0.0
    - pytorch >=1,<3
    - qdrant-client >=1.3.1,<2.0.0
    - rank-bm25 >=0.2.2,<0.3.0
    - rapidfuzz >=3.1.1,<4.0.0
    - rapidocr-onnxruntime >=1.3.2,<2.0.0  # [py<312]
    - rdflib =7.0.0
    - requests-toolbelt >=1.0.0,<2.0.0
    - rspace_client >=2.5.0,<3.0.0
    - scikit-learn >=1.2.2,<2.0.0
    - sentence-transformers >=2.0.0,<3.0.0
    - sqlite-vss >=0.1.2,<0.2.0
    - streamlit >=1.18.0,<2.0.0
    - sympy >=1.12.0,<2.0.0
    - telethon >=1.28.5,<2.0.0
    - tenacity >=8.1.0,<9.0.0
    - tiktoken >=0.3.2,<0.6.0  # [py>=39]
    - timescale-vector >=0.0.1,<0.0.2
    - tqdm >=4.48.0
    - transformers >=4.0.0,<5.0.0
    - typer >=0.9.0,<0.10.0
    - upstash-redis >=0.15.0,<0.16.0
    - xata >=1.0.0,<2.0.0
    - xmltodict >=0.13.0,<0.14.0

test:
  imports:
    - langchain
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/langchain-ai/langchain
  doc_url: https://python.langchain.com/
  dev_url: https://github.com/hwchase17/langchain
  summary: Building applications with LLMs through composability
  description: |
    LangChain is a framework for developing applications powered by language models (LLMs).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
