{% set name = "langchain" %}
{% set version = "0.3.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/langchain-ai/langchain/archive/refs/tags/{{ name }}=={{ version }}.tar.gz
  sha256: c3ea5fc14df9cd791fbf68a9b0f55928674006d64e229d4af0eb642f099cef09

build:
  number: 0
  skip: True # [py<39]
  script:
    - {{ PYTHON }} -m pip install ./libs/langchain -vv --no-deps --no-build-isolation
  entry_points:
    - langchain-server = langchain.server:main

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - aiohttp >=3.8.3,<4.0.0
    - async-timeout >=4.0.0,<5.0.0  # [py<311]
    - langchain-core >=0.3.25,<0.4.0
    - langchain-text-splitters >=0.3.3,<0.4.0
    - langsmith >=0.1.17,<0.3.0
    - numpy >=1.22.4,<2.0.0  # [py<312]
    - numpy >=1.26.2,<3.0.0  # [py>=312]
    - pydantic >=2.7.4,<3.0.0
    - python
    - pyyaml >=5.3
    - requests >=2.0.0,<3.0.0
    - sqlalchemy >=1.4,<3
    - tenacity >=8.1.0,!=8.4.0,<10.0.0

test:
  imports:
    - langchain
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/langchain-ai/langchain
  doc_url: https://python.langchain.com/
  dev_url: https://github.com/hwchase17/langchain
  summary: Building applications with LLMs through composability
  description: |
    LangChain is a framework for developing applications powered by language models (LLMs).
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YYYasin19
